# Jasypt encryption
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: hong8159

#Server Encoding
server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true


#Spring Setting
spring :
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ENC(tj8W05hwc8lT/+gmdkaPy6X7I7ryAEzjvbaI8botrEvvwhaBVaHL5uYDT0TzTCulXqcQYHWu0z5gqG6CeoSfygFDtnfDNYZH)
    username: ENC(keKb5G3iZVw11hGUnpqN7w==)
    password : ENC(eBmL6ocDbYOTyWeuO6cOnA==)

  jpa:
    show-sql : true
    database-platform: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: update




