POST http://localhost:8080/api/members
Content-Type: application/json

{
     "email" : "grayson@naver.com",
     "memberId" : "grayson",
     "name" : "홍근호",
     "password" : "password",
     "phoneNumber" : "010-7122-8159",
     "birthDate" : "1994-01-14"
}



###
###
GET http://localhost:8080/api/members/5






